### ISSUE TITLE
Strange Array

### ISSUE THREAD

**Issue by maximiliano2018** [amcolash/MMM-json-feed#12]
Hi Amcolash!

Please, can you help me?
Im trying read this json, but i can do it work.

https://wapi.im/dashboard/ receive messages in this json format.

How can i get "Content" por example? (content="Peces del Mar"), chatid and name?
Very thanks in advance,

{
"messages":[
{
"finalAccuracy":null,
"description":null,
"quotedMsgObj":null,
"quotedStanzaID":null,
"clientUrl":null,
"labels":{},
"recvFresh":true,
"caption":null,
"isForwarded":false,
"streamable":null,
"protocolMessageKey":null,
"multicast":null,
"clearMedia":null,
"finalSpeed":null,
"mentionedJidList":null,
"quotedRemoteJid":null,
"shareDuration":null,
"quotedMsg":null,
"chatId":"5491155172299@c.us",
"speed":null,
"paymentTransactionTimestamp":null,
"broadcast":false,
"accuracy":null,
"content":"Peces del mar",
"cid":null,
"isPSA":false,
"directPath":null,
"width":null,
"mediaKey":null,
"isLink":null,
"type":"chat",
"duration":null,
"finalThumbnail":null,
"finalDegrees":null,
"star":false,
"chat":{
"labels":null,
"presence":{
"chatstates":{
},
"id":"5491155172299@c.us"
},
"groupMetadata":null,
"name":"Mirta E. Pereira",
"isAnnounceGrpRestrict":null,
"muteExpiration":0,
"modifyTag":191752,
"pin":0,
"unreadCount":0,
"pendingMsgs":false,
"msgs":null,
"id":"5491155172299@c.us",
"kind":"chat",
"changeNumberOldJid":null,
"lastReceivedKey":{
"_serialized":"false_5491155174399@c.us_60D591509F9F1BEDCF15EE0EC9ACE5C5",
"fromMe":false,
"id":"60D591509F9F1BEDCF15EE0EC9ACE5C5",
"remote":"5491155172299@c.us"
},
"t":1537237565,
"archive":false,
"contact":{
"labels":{
},
"verifiedName":null,
"sectionHeader":null,
"name":"Pereira",
"isPSA":false,
"isWAContact":true,
"profilePicThumbObj":{
"eurl":"https://pps.whatsapp.net/v/t61.11540-24/16827015_286021331814940_6247275763075121152_n.jpg?oe=5BA456A7&oh=0288b628ffd5537737610358fe8b5227",
"id":"5491155172299@c.us",
"img":"https://dyn.web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F16827015_286021331814940_6247275763075121152_n.jpg%3Foe%3D5BA456A7%26oh%3D0288b628ffd5537737610358fe8b5227&t=s&u=5491155174399%40c.us&i=1458001268",
"imgFull":"https://dyn.web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F16827015_286021331814940_6247275763075121152_n.jpg%3Foe%3D5BA456A7%26oh%3D0288b628ffd5537737610358fe8b5227&t=l&u=5491155174399%40c.us&i=1458001268",
"raw":null,
"tag":"1458001268"
},
"type":"in",
"isBusiness":false,
"statusMute":false,
"isEnterprise":false,
"isContactBlocked":false,
"isVerified":null,
"shortName":"Mirta",
"msgs":null,
"isUser":true,
"isHighLevelVerified":null,
"plaintextDisabled":true,
"id":"5491155172299@c.us",
"verifiedLevel":null,
"pushname":"Pereira",
"isMe":false,
"isMyContact":true,
"formattedName":"Pereira"
},
"notSpam":true,
"changeNumberNewJid":null,
"isGroup":false,
"isReadOnly":false
},
"mediaData":{
},
"uploadhash":null,
"streamingSidecar":null,
"vcardList":null,
"isMMS":false,
"recipients":null,
"invis":false,
"paymentStatus":null,
"mimetype":null,
"font":null,
"size":null,
"title":null,
"finalLng":null,
"paymentNoteMsg":null,
"author":null,
"currency":null,
"filename":null,
"filehash":null,
"thumbnail":null,
"textColor":null,
"isNewMsg":true,
"from":"5491155172299@c.us",
"urlText":null,
"id":"false_5491155172299@c.us_08CA24BE16760A26C0F87C85F6228017",
"isMedia":false,
"ack":-1,
"comment":null,
"templateParams":null,
"sender":{
"labels":{
},
"verifiedName":null,
"sectionHeader":null,
"name":"Pereira",
"isPSA":false,
"isWAContact":true,
"profilePicThumbObj":{
"eurl":"https://pps.whatsapp.net/v/t61.11540-24/16827015_286021331814940_6247275763075121152_n.jpg?oe=5BA456A7&oh=0288b628ffd5537737610358fe8b5227",
"id":"5491155172299@c.us",
"img":"https://dyn.web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F16827015_286021331814940_6247275763075121152_n.jpg%3Foe%3D5BA456A7%26oh%3D0288b628ffd5537737610358fe8b5227&t=s&u=5491155174399%40c.us&i=1458001268",
"imgFull":"https://dyn.web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F16827015_286021331814940_6247275763075121152_n.jpg%3Foe%3D5BA456A7%26oh%3D0288b628ffd5537737610358fe8b5227&t=l&u=5491155174399%40c.us&i=1458001268",
"raw":null,
"tag":"1458001268"
},
"type":"in",
"isBusiness":false,
"statusMute":false,
"isEnterprise":false,
"isContactBlocked":false,
"isVerified":null,
"shortName":"Mirta",
"msgs":null,
"isUser":true,
"isHighLevelVerified":null,
"plaintextDisabled":true,
"id":"5491155172299@c.us",
"verifiedLevel":null,
"pushname":"Pereira",
"isMe":false,
"isMyContact":true,
"formattedName":"Pereira"
},
"sequence":null,
"amount1000":null,
"lat":null,
"receiverJid":null,
"notifyName":"",
"pageCount":null,
"finalLat":null,
"urlNumber":null,
"matchedText":null,
"t":1537238750,
"richPreviewType":null,
"isGroupMsg":false,
"loc":null,
"timestamp":1537238750,
"body":"Peces del mar",
"gifAttribution":null,
"backgroundColor":null,
"degrees":null,
"isLive":null,
"quotedParticipant":null,
"self":"in",
"finalTimeOffset":null,
"isNotification":false,
"lng":null,
"height":null,
"subtype":null,
"isGif":null,
"to":"5491145288567@c.us",
"canonicalUrl":null
}
]
}

**Comment by amcolash** [comment]
Please know that the above url is not json. You will need to figure out authentication yourself on that one... It was not a feature. I added in a new feature for arrays using the config `arrayName`.

You will need to update...
```
cd MagicMirror/modules/MMM-json-feed
git pull
```

And use a config like this:
```
{
    module: 'MMM-json-feed',
    position: 'bottom_bar',
    config: {
      urls: [
        'https://wapi.im/dashboard/',
      ],
      arrayName: "messages",
      values: [ "content", "chatId", "name" ]
    }
  }
```
