### ISSUE TITLE
screenshot! 

### ISSUE THREAD

**Issue by E3V3A** [amcolash/MMM-json-feed#2]

**Comment by amcolash** [comment]
Note to self: Add a screenshot to the README for this.

**Comment by E3V3A** [comment]
Thanks! I'm going through 100's of MMM's to find what I like and need, but bloody hell 90% doesn't have any pictures.

**Comment by amcolash** [comment]
Fixed with:
e299190a0669e9fc512092977b83a743e5277af0
11d871dd5946722d49343f1179a7cd3ea30a9907
63b1affaf4c01eec47da66f5997b97efc58c7e0f

Yay :grin:
