### ISSUE TITLE
Formating issue

### ISSUE THREAD

**Issue by vonglahn** [amcolash/MMM-json-feed#7]
We have a jason feed like this:

{
"Wind [m/s]": 30.2,
"Druck [hPa]": 1000.1
}

But the values are displayed like this (note the values in brakets)
Wind [M/s]: 30.2,
Druck [H Pa]: 1000.1

Do you know how I correct this?

**Comment by amcolash** [comment]
You will need to change your `config.js` to include the option `prettyName: false`. Most times this is useful if your json has odd casing or otherwise. Let me know if that works for you.

**Comment by vonglahn** [comment]
This works

Thank you
